// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	TicketID  int64              `json:"ticket_id"`
	Quantity  int32              `json:"quantity"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Ticket struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	TotalStock int32              `json:"total_stock"`
	Price      int32              `json:"price"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
