events {
    worker_connections 2048; # Максимум одновременных соединений на воркер
}

http {
    # Группа наших Go API серверов
    upstream api_backend {
        # Имя сервиса из docker-compose (Nginx сам зарезолвит его IP в Docker-сети)
        server api:8888;

        # Если запустим несколько инстансов (docker compose up --scale api=3),
        # Nginx будет автоматически балансировать нагрузку по Round-Robin.
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_backend;

            # Прокидываем оригинальные заголовки клиента
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_request_headers on;
            # Таймауты для быстрой отработки под нагрузкой
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }

        # Эндпоинт для проверки здоровья самого Nginx
        location /healthz {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}